#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Clean the Directory for EdgeGallery Offline Tarball File
  file:
    path: "{{ TARBALL_PATH }}"
    state: absent
  when: TARBALL_PATH_CLEANUP

- name: Create the Directory for EdgeGallery Offline Tarball File
  file:
    path: "{{ TARBALL_PATH }}"
    state: directory
  register: pathCreated

- name: Unarchive EdgeGallery Offline Tarball File
  unarchive:
    src: "{{ TARBALL_FILE }}"
    dest: "{{ TARBALL_PATH }}"
    copy: "{{ COPY_TAR_TO_TARGET }}"
  register: unarchivePackage
  when: pathCreated is succeeded

- name: Create Group eggroup
  group:
    name: "{{ EGGROUP_NAME }}"
    gid: "{{ EGGROUP_GID }}"

- name: Create User eguser
  user:
    name: "{{ EGUSER_NAME }}"
    uid: "{{ EGUSER_UID }}"
    group: "{{ EGGROUP_NAME }}"
    create_home: no

- name: Create Appstore Packages Directory
  file:
    path: "{{ APPSTORE_PACKAGES }}"
    state: directory
    group: "{{ EGGROUP_NAME }}"
    owner: "{{ EGUSER_NAME }}"
    mode: 0750

- name: Create File-System VM Images Directory
  file:
    path: "{{ FILE_SYSTEM_PACKAGES }}"
    state: directory
    group: "{{ EGGROUP_NAME }}"
    owner: "{{ EGUSER_NAME }}"
    mode: 0750
