version: "3"
services:
  mecm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-fe:latest
    ports:
         - 30093:8443
    environment:
      LOG_DIR: /var/log/mecm-fe
      LOG_FILE_NAME: mecm-fe    
      LISTEN_IP: ${ENV_IP}
      fieldPath: status.podIP
      SC_ADDRESS: http://${ENV_IP}:30100
      AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
      COOKIE_NAME: MECMSESSIONID
      CLIENT_ID: mecm-fe
      CLIENT_SECRET: te9Fmv%qaq
      SSL_ENABLED: "false"
      CLIENT_ID: bWVjbS1mZQ==
      