version: '3'
services:
  mep-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep-fe:v1.1.1
    ports:
      - 30095:8100
    depends_on:
      - postgres
      - kong
      - mep
      - mep-auth
      - mep-dns
      - mep-elasticsearch
     

  postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3  
    environment: 
      POSTGRES_USER: admin
      POSTGRES_DB: kong 
      POSTGRES_PASSWORD: admin-Pass123
      POSTGRES_INITDB_ARGS: password  
    volumes:
      - ./postgres-data:/docker-entrypoint-initdb.d/
     
  kong:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/kong:2.0.4-ubuntu
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong-Pass123
   
      
         
  mep:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep:v1.1.1
    ports:
      - 30443:8443
    environment: 
       MEPSERVER_APIGW_HOST: "localhost"
       MEPSERVER_APIGW_PORT: "8444"
       MEPSERVER_CERT_DOMAIN_NAME: "edgegallery"
       ROOT_KEY: "$(openssl rand -base64 256 | tr -d '\n' | tr -dc '[[:alnum:]]' | cut -c -256)"
       TLS_KEY: te9Fmv%qaq  
 
 mep-auth:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepauth:v1.1.1
    ports:
      - 10443
    environment:   
      MEPAUTH_APIGW_HOST: "localhost"
      MEPAUTH_APIGW_PORT: "8444"
      MEPAUTH_CERT_DOMAIN_NAME: "edgegallery"
      MEPAUTH_DB_NAME: kong
      MEPAUTH_DB_USER: kong 
      MEPAUTH_DB_PASSWD: kong-Pass123
      
  
  mep-dns:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep-dns-server:v1.1.1
    ports:
      - 30444:53

  mep-elasticsearch:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/elasticsearch:7.9.0
    ports:
      - 9200
    environment:
      discovery.type: "single-node"
    
    
