version: "3"
services:      
    appstore-fe:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-fe:v1.1.1
        ports:
          - 30091:8443
        depends_on:
          - postgres
        environment: 
            LOG_DIR: /usr/app/log
            LOG_FILE_NAME: "appstore-fe"
            LISTEN_IP: appstore-be
            SC_ADDRESS: http://${ENV_IP}:30100
            AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
            COOKIE_NAME: APPSTORESESSIONID
            CLIENT_ID: "appstore-fe"
            CLIENT_SECRET: "te9Fmv%qaq"
            SSL_ENABLED: "false"
            IS_SECURE_BACKEND: "false"
            
    appstore-be:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-be:v1.1.1
        depends_on:
          - postgres
        environment:
            LOG_DIR: /usr/app/log
            LISTEN_IP: appstore-be
            SC_ADDRESS: http://${ENV_IP}:30100
            POSTGRES_IP: postgres
            POSTGRES_PORT: "5432"
            POSTGRES_DB_NAME: "appstoredb"
            POSTGRES_USERNAME: "appstore"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
            APPSTORE_REPO_PASSWORD: Harbor@12345
            APPSTORE_REPO_USERNAME: admin
            APPSTORE_REPO_ENDPOINT: ${ENV_IP}
            DEV_REPO_PASSWORD: Harbor@12345
            DEV_REPO_USERNAME: admin
            SSL_ENABLED: "false"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    postgres:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3
        environment:
            POSTGRES_USER: "appstore"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            POSTGRES_DB: "appstoredb"
#        volumes:
#          - ./postgres-data:/docker-entrypoint-initdb.d
