version: "3"
services:      
    appstore-fe:
      image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-fe:v1.1.1
      ports:
        - 30091:8443
      depends_on:
        - postgres
      environment: 
        LOG_DIR: /usr/app/log
        LOG_FILE_NAME: "appstore-fe"
        LISTEN_IP: appstore-be
        SC_ADDRESS: https://${ENV_IP}:30100
        AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
        COOKIE_NAME: APPSTORESESSIONID
        CLIENT_ID: "appstore-fe"
        CLIENT_SECRET: "te9Fmv%qaq"
        SSL_ENABLED: "true"
        IS_SECURE_BACKEND: "true"
        SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
        SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
        SSL_KEY_STORE_TYPE: PKCS12
        SSL_KEY_ALIAS: edgegallery
      volumes:
        - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
            
    appstore-be:
      image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-be:v1.1.1
      ports:
        - 8099:8099
      depends_on:
        - postgres
      environment:
        LOG_DIR: /usr/app/log
        LISTEN_IP: appstore-be
        SC_ADDRESS: https://${ENV_IP}:30100
        POSTGRES_IP: postgres
        POSTGRES_PORT: "5432"
        POSTGRES_DB_NAME: "appstoredb"
        POSTGRES_USERNAME: "appstore"
        POSTGRES_PASSWORD: "te9Fmv%qaq"
        AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
        APPSTORE_REPO_PASSWORD: Harbor@12345
        APPSTORE_REPO_USERNAME: admin
        APPSTORE_REPO_ENDPOINT: ${ENV_IP}
        DEV_REPO_PASSWORD: Harbor@12345
        DEV_REPO_USERNAME: admin
        SSL_ENABLED: "true"
        SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
        SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
        SSL_KEY_STORE_TYPE: PKCS12
        SSL_KEY_ALIAS: edgegallery
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12

    postgres:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3
        environment:
            POSTGRES_USER: "appstore"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            POSTGRES_DB: "appstoredb"
#        volumes:
#          - ./postgres-data:/docker-entrypoint-initdb.d
