---

# IaaS Deployment on Master and Worker Node
- hosts: master
  become: yes
  vars:
    - OPERATION: install
    - EG_MODE: all
    - NODE_MODE: muno
    - K8S_NODE_TYPE: master
  vars_files:
    - ./var.yml
    - ./default-var.yml
  roles:
    - init
    - k8s
    - eg_prepare

- hosts: worker
  become: yes
  vars:
    - OPERATION: install
    - EG_MODE: all
    - NODE_MODE: muno
    - K8S_NODE_TYPE: worker
  vars_files:
    - ./var.yml
    - ./default-var.yml
  roles:
    - init
    - k8s
    - eg_prepare

# PaaS Deployment on Master
- hosts: master
  become: yes
  vars:
    - OPERATION: install
    - EG_MODE: all
    - NODE_MODE: muno
    - K8S_NODE_TYPE: master
  vars_files:
    - ./var.yml
    - ./default-var.yml
  roles:
    - mep
    - mecm-mepm
    - user-mgmt
    - mecm-meo
    - mecm-fe
    - appstore
    - developer
    - atp
    - eg_check
