---

- hosts: master
  become: yes
  vars:
    - OPERATION: install
    - EG_MODE: controller
    - NODE_MODE: aio
    - K8S_NODE_TYPE: master
  vars_files:
    - ./var.yml
    - ./default-var.yml
  roles:
    - init
    - k8s
    - eg_prepare
    - user-mgmt
    - mecm-meo
    - mecm-fe
    - appstore
    - developer
    - atp
    - eg_check
