#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Ensure User Group "docker" Exists
  group:
    name: docker
    state: present
  register: dockerGroup

- name: Deploy MECM-MEO
  shell: |
    helm install --wait mecm-meo-edgegallery {{ HELM_CHARTS_PATH }}/edgegallery/mecm-meo-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress=https://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }} \
    --set global.oauth2.clients.mecm.clientSecret={{ oauth2ClientPassword }} \
    --set images.mecmFe.repository={{ mecm_fe_images_mecmFe_repository }} \
    --set images.initservicecenter.repository={{ mecm_fe_images_initservicecenter_repository }} \
    --set images.mecmFe.tag={{ mecm_fe_images_mecmFe_tag }} \
    --set images.initservicecenter.tag={{ mecm_fe_images_initservicecenter_tag }} \
    --set images.mecmFe.pullPolicy={{ mecm_fe_images_mecmFe_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ mecm_fe_images_initservicecenter_pullPolicy }} \
    --set global.ssl.enabled={{ mecm_fe_global_ssl_enabled }} \
    --set global.ssl.secretName={{ meo_ssl_secretName }} \
    --set global.ssl.enabled={{ meo_global_ssl_enabled }} \
    --set images.inventory.repository={{ meo_images_inventory_repository }} \
    --set images.appo.repository={{ meo_images_appo_repository }} \
    --set images.apm.repository={{ meo_images_apm_repository }} \
    --set images.postgres.repository={{ meo_images_postgres_repository }} \
    --set images.inventory.tag={{ meo_images_inventory_tag }} \
    --set images.appo.tag={{ meo_images_appo_tag }} \
    --set images.apm.tag={{ meo_images_apm_tag }} \
    --set images.postgres.tag={{ meo_images_postgres_tag }} \
    --set images.inventory.pullPolicy={{ meo_images_inventory_pullPolicy }} \
    --set images.appo.pullPolicy={{ meo_images_appo_pullPolicy }} \
    --set images.apm.pullPolicy={{ meo_images_apm_pullPolicy }} \
    --set images.postgres.pullPolicy={{ meo_images_postgres_pullPolicy }} \
    --set mecm.docker.fsgroup={{ dockerGroup.gid }} \
    --set mecm.docker.dockerRepoUserName=admin \
    --set mecm.docker.dockerRepopassword={{ HARBOR_ADMIN_PASSWORD }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set mecm.repository.dockerRepoEndpoint={{ PORTAL_IP }} \
    --set mecm.repository.sourceRepos="repo={{ PORTAL_IP }} userName=admin password={{ HARBOR_ADMIN_PASSWORD }}" \
    --set mecm.postgres.postgresPass={{ postgresPassword }} \
    --set mecm.postgres.inventoryDbPass={{ postgresPassword }} \
    --set mecm.postgres.appoDbPass={{ postgresPassword }} \
    --set mecm.postgres.apmDbPass={{ postgresPassword }}
  no_log: true
  ignore_errors: yes
  register: mecmMeoout

- name: Output of "Deploy MECM-MEO" task
  debug:
    msg: "rc: {{mecmMeoout.rc}}, stderr: {{mecmMeoout.stderr}}, stderr_lines: {{mecmMeoout.stderr_lines}}, stdout: {{mecmMeoout.stdout}}, stdout_lines: {{mecmMeoout.stdout_lines}}"
  when: mecmMeoout is failed

- name: Failing as task "Deploy MECM-MEO" failed
  fail:
    msg: The task Deploy MECM-MEO has failed
  when: mecmMeoout is failed

- name: Check MECM-MEO Status
  uri:
    url: "https://{{ PORTAL_IP }}:{{ item }}/v1/health"
    validate_certs: no
  loop:
    - 30201/appo
    - 30202/apm
    - 30203/inventory
