---

- name: Check EG_MODE for MECM_MEO
  fail:
    msg: "Could not {{ OPERATION }} MECM_MEO with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "controller"

- name: Check whether MECM_MEO is Deployed
  shell: helm list | grep mecm-meo-edgegallery
  register: mecmMeoDeployed
  ignore_errors: yes

- debug:
    msg: MECM_MEO is already deployed, no need to be deployed again
  when: mecmMeoDeployed is succeeded and OPERATION == "install"

- debug:
    msg: MECM_MEO is not deployed, will be deployed
  when: mecmMeoDeployed is failed and OPERATION == "install"

- debug:
    msg: MECM_MEO is already deployed, will be undeployed
  when: mecmMeoDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: MECM_MEO is not deployed, no need to be undeployed anymore
  when: mecmMeoDeployed is failed and OPERATION == "uninstall"

- name: Deploy MECM_MEO Online
  include: "deploy_online.yml"
  when: mecmMeoDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy MECM_MEO Offline
  include: "deploy_offline.yml"
  when: mecmMeoDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy MECM_MEO
  include: "undeploy.yml"
  when: mecmMeoDeployed is succeeded and OPERATION == "uninstall"
