############################################################################
# Copyright 2021 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

HELM_OFFLINE_DIR: "{{ TARBALL_PATH }}/helm"
HELM_CHARTS_OFFLINE_DIR: "{{ HELM_OFFLINE_DIR }}/helm-charts"
HELM_CHARTS_EG: "{{ HELM_CHARTS_OFFLINE_DIR }}/edgegallery"
HELM_CHARTS_STABLE: "{{ HELM_CHARTS_OFFLINE_DIR }}/stable"


EG_HELM_REPO: "http://192.168.100.143:30002/chartrepo/edgegallery_helm_chart"

EG_HELM_LIST_CONTROLLER:
  - servicecenter
  - usermgmt
  - developer
  - appstore
  - mecm-meo
  - atp

EG_HELM_LIST_EDGE:
  - mecm-mepm
  - mep

STABLE_NGINX_HELM_URL: https://kubernetes-charts.storage.googleapis.com/nginx-ingress-1.41.2.tgz
STABLE_NGINX_HELM_NAME: nginx-ingress-1.41.2.tgz

STABLE_NFS_HELM_URL: https://kubernetes-charts.storage.googleapis.com/nfs-client-provisioner-1.2.8.tgz
STABLE_NFS_HELM_NAME: nfs-client-provisioner-1.2.8.tgz
