version: "3"
services:
  mecm-applcm-apprulemgr：
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appclm-apprulemgr:latest
    environment:
      LOG_DIR: /usr/app/log
      MEP_SERVER_ADDR: mep-mm5.mep
      MEP_SERVER_PORT: 80 
      APPRULEMGR_DB_ADAPTER: pgDb
      LISTEN_IP: ${ENV_IP}
      JWT_PUBLIC_KEY: publicKey
      APPRULEMGR_DB_PASSWORD：te9Fmv%qaq
  mecm-applcm-k8splugin：
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-k8splugin:latest
    environment:     
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      K8S_PLUGIN_DB_PASSWORD: te9Fmv%qaq
      JWT_PUBLIC_KEY: publicKey
      
  mecm-applcm-lcmcontroller：
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-k8splugin:latest
    environment:     
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      API_GW_ADDR: mepauth.mep
      API_GW_PORT: "10443"
      K8S_PLUGIN: mecm-mepm-k8splugin
      K8S_PLUGIN_PORT: "8095"
      OPENSTACK_PLUGIN: mecm-mepm-osplugin
      OPENSTACK_PLUGIN_PORT: "8234" 
      LISTEN_IP: ${ENV_IP}
      LCM_CNTLR_DB_PASSWORD：te9Fmv%qaq
      JWT_PUBLIC_KEY：publicKey
  
  mepm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepm-fe:latest
    environment:     
      ports:
        - 30097:8443
        
  mepm-postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres:12.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: te9Fmv%qaq
      POSTGRES_DB: root
      
      