############################################################################
# Copyright 2021 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

---

- name: Copy Config Files to K8S Offline Package
  copy:
    src: "{{ item }}"
    dest: "{{ K8S_OFFLINE_DIR }}/k8s"
  loop:
    - 10-kubeadm.conf
    - k8s.conf
    - kubelet.service
    - calico.yaml
    - metric-server.yaml

- name: Download nginx-app.yaml File
  get_url:
    url: https://k8s.io/examples/application/nginx-app.yaml
    dest: "{{ K8S_OFFLINE_DIR }}/k8s"

- name: Change nginx Version in nginx-app.yaml File to be Stable
  replace:
    path: "{{ K8S_OFFLINE_DIR }}/k8s/nginx-app.yaml"
    regexp: "nginx:.*"
    replace: "nginx:stable"

- name: Download K8S Related Packages
  shell: "scp -P {{ FTP_SSH_PORT }} {{ FTP_USER }}@{{ FTP_SERVER }}:/home/jenkins/kube/{{ ARCH }}/{{ item }} {{ K8S_OFFLINE_DIR }}/k8s"
  loop:
    - kubectl
    - kubeadm
    - kubelet

- name: Download Socat and Conntrack ARM64 Deb
  get_url:
    url: "{{ item }}"
    dest: "{{ K8S_OFFLINE_DIR }}/tools"
  loop:
    - https://mirrors.aliyun.com/ubuntu-ports/pool/main/s/socat/socat_1.7.3.2-2ubuntu2_arm64.deb
    - http://ports.ubuntu.com/pool/main/c/conntrack-tools/conntrack_1.4.4+snapshot20161117-6ubuntu2_arm64.deb
  when: ARCH == "arm64"

- name: Download Socat and Conntrack X86 Deb
  get_url:
    url: "{{ item }}"
    dest: "{{ K8S_OFFLINE_DIR }}/tools"
  loop:
    - http://archive.ubuntu.com/ubuntu/pool/main/s/socat/socat_1.7.3.2-2ubuntu2_amd64.deb
    - http://archive.ubuntu.com/ubuntu/pool/main/c/conntrack-tools/conntrack_1.4.4+snapshot20161117-6ubuntu2_amd64.deb
  when: ARCH == "amd64"
