HELM_VERSION: v3.2.4
HELM_TARBALL_FILE: "{{ TARBALL_PATH }}/helm/helm-{{ HELM_VERSION }}-linux-{{ ARCH }}.tar.gz"
HELM_OFFLINE_DIR: "{{ TARBALL_PATH }}/helm"
HELM_CHARTS_DIR: "{{ HELM_OFFLINE_DIR }}/helm-charts"
HELM_REPO_CONTAINER_NAME: helm-repo
HELM_REPO_IMAGE: nginx:stable

HARBOR_DIR: "{{ TARBALL_PATH }}/harbor"
HARBOR_DATA_VOLUME: "/root/harbor/data_volume"

CERT_VALIDITY_IN_DAYS: 365

keystorePassword: te9Fmv%qaq
keystoreType: PKCS12
keyAlias: edgegallery
cert_pwd: te9Fmv%qaq

servicecenter_images_repository: eg-common/service-center
servicecenter_images_pullPolicy: IfNotPresent
servicecenter_global_ssl_enabled: true
servicecenter_global_ssl_secretName: edgegallery-ssl-secret
