############################################################################
# Copyright 2021 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

---

- name: Set Other Helm List
  set_fact:
    OTHER_HELM_URL_LIST: "{{ STABLE_HELM_URL_LIST }}"
    OTHER_HELM_NAME_LIST: "{{ STABLE_HELM_NAME_LIST }}"

- name: Pull Other Helm Charts
  get_url:
    url: "{{ item }}"
    dest: "{{ HELM_CHARTS_STABLE }}"
  loop: "{{ OTHER_HELM_URL_LIST }}"
  register: pullOtherHelmCharts
  ignore_errors: yes

- name: Copy From Local Directory
  shell: "scp {{ FTP_SERVER }}:/home/helm-charts-stable/{{ item }} {{ HELM_CHARTS_STABLE }}"
  loop: "{{ OTHER_HELM_NAME_LIST }}"
  when: pullOtherHelmCharts is failed
