kind: ServiceAccount
apiVersion: v1
metadata:
  name: edgegallery-secondary-ep-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multi-ip-controller
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["endpoints", "events"]
    verbs: ["*"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-update-secondary-endpoints
subjects:
  - kind: ServiceAccount
    name: edgegallery-secondary-ep-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: multi-ip-controller
  apiGroup: rbac.authorization.k8s.io