############################################################################
# Copyright 2020 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################
global:
  servicecenter:
    enabled: true
  usermgmt:
    enabled: true
  appstore:
    enabled: true
  developer:
    enabled: true
  atp:
    enabled: true
  mecm-meo:
    enabled: true
  mecm-mepm:
    enabled: true
  mep:
    enabled: true
  persistence:
    enabled: true
    storageClassName: nfs-client
  ingress:
    enabled: false
    tls:
      enabled: false
      secretName: edgegallery-ingress-secret
    annotations:
      bodySize: 20m
    hosts:
      auth: 192.168.1.11:30067
      developer: 192.168.1.11:30092
      appstore: 192.168.1.11:30091
      mecm: 192.168.1.11:30093
      atp: 192.168.1.11:30094
  ssl:
    enabled: true
    secretName: edgegallery-ssl-secret
  oauth2:
    authServerAddress: https://192.168.1.11:30067
    clients:
      appstore:
        clientId: appstore-fe
        clientUrl: https://192.168.1.11:30091
      developer:
        clientId: developer-fe
        clientUrl: https://192.168.1.11:30092
      mecm:
        clientId: mecm-fe
        clientUrl: https://192.168.1.11:30093
      atp:
        clientId: atp-fe
        clientUrl: https://192.168.1.11:30094
      lab:
        clientId: lab-fe
        clientUrl: https://192.168.1.11:30096
jwt:
  secretName: user-mgmt-jwt-secret

images:
  service-center:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/service-center
    tag: latest 
    pullPolicy: IfNotPresent


  usermgmt:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/user-mgmt
    tag: v1.2.0
    pullPolicy: IfNotPresent
  postgres:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres
    tag: 12.3
    pullPolicy: IfNotPresent
  redis:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/redis
    tag: 6.0.3
    pullPolicy: IfNotPresent
  initservicecenter:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/curl
    tag: 7.75.0
    pullPolicy: IfNotPresent

  appstoreBe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-be
    tag: v1.2.0
    pullPolicy: IfNotPresent
  appstoreFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/appstore-fe
    tag: v1.2.0
    pullPolicy: IfNotPresent

  developerBe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-be
    tag: v1.2.0
    pullPolicy: IfNotPresent
  developerFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-fe
    tag: v1.2.0
    pullPolicy: IfNotPresent
  toolChain:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/tool-chain
    tag: v1.2.0
    pullPolicy: IfNotPresent
  portingAdvisor:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/porting-advisor
    tag: latest
    pullPolicy: IfNotPresent

  atp:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/atp-be
    tag: v1.2.0
    pullPolicy: IfNotPresent
  atpFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/atp-fe
    tag: v1.2.0
    pullPolicy: IfNotPresent
 
  mecmFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-fe
    tag: v1.2.0
    pullPolicy: IfNotPresent
  inventory:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-inventory
    tag: v1.2.0
    pullPolicy: IfNotPresent
  appo:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appo
    tag: v1.2.0
    pullPolicy: IfNotPresent
  apm:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apm
    tag: v1.2.0
    pullPolicy: IfNotPresent
   
  lcmcontroller:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm
    tag: v1.2.0
    pullPolicy: IfNotPresent
  k8splugin:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-k8splugin
    tag: v1.2.0
    pullPolicy: IfNotPresent
  osplugin:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-osplugin
    tag: v1.2.0
    pullPolicy: IfNotPresent
  apprulemgr:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apprulemgr
    tag: v1.2.0
    pullPolicy: IfNotPresent
  mepmFe:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepm-fe
    tag: v1.2.0
    pullPolicy: IfNotPresent
 
  mep:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep
    tag: v1.2.0
    pullPolicy: IfNotPresent
  mepauth:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepauth
    tag: v1.2.0
    pullPolicy: IfNotPresent
  kong:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/kong
    tag: 2.0.4-ubuntu
    pullPolicy: IfNotPresent
  dns:
    repository: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mep-dns-server
    tag: v1.2.0
    pullPolicy: IfNotPresent
  elasticsearch:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/elasticsearch
    tag: 7.9.0
    pullPolicy: IfNotPresent
  ntp:
    repository: swr.ap-southeast-1.myhuaweicloud.com/eg-common/cturra/ntp
    tag: latest
    pullPolicy: IfNotPresent
  
# appShare config
appShare:
  enabled: true
  platformName: EdgeGallery AppStore
  platformUrl:  https://192.168.1.11:30099
  atpReportUrl:  https://192.168.1.11:30094/#/atpreport?taskid=%s
  appDetailUrl:  https://192.168.1.11:30091/#/detail?appId=%s&packageId=%s