version: "3"
services:
  tool-chain:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/tool-chain:v1.1.1
    environment:
      LOG_DIR: /var/log/tool-chain
      SC_ADDRESS: https://${ENV_IP}:30100
      LISTEN_IP: tool-chain
      SSL_ENABLED: "true"
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: PKCS12
      SSL_KEY_ALIAS: edgegallery
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
      - /opt/portadv/portadmin:/opt/portadv/portadmin

  porting-advisor:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/porting-advisor:latest
    privileged: true
    volumes:
      - /opt/portadv/portadmin:/opt/portadv/portadmin

  postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres:12.3
    environment:
      POSTGRES_USER: "developer"
      POSTGRES_PASSWORD: "te9Fmv%qaq"
      POSTGRES_DB: "developerdb"
    volumes:
      - ./postgres-data:/docker-entrypoint-initdb.d/

  developer-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-fe:v1.1.1
    ports:
      - 30092:8443
    depends_on:
      - postgres
      - tool-chain
      - porting-advisor
    environment:
      LOG_DIR: /var/log/developer-fe
      LOG_FILE_NAME: "developer-fe"
      LISTEN_IP: developer-be
      SC_ADDRESS: https://${ENV_IP}:30100
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
      COOKIE_NAME: DEVELOPERSESSIONID
      CLIENT_ID: "developer-fe"
      CLIENT_SECRET: "te9Fmv%qaq"
      SSL_ENABLED: "true"
      IS_SECURE_BACKEND: "true"
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: PKCS12
      SSL_KEY_ALIAS: edgegallery
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12

  developer-be:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-be:v1.1.1
    depends_on:
      - postgres
      - tool-chain
      - porting-advisor
    environment:
      CLIENT_ID: "developer-fe"
      CLIENT_SECRET: "te9Fmv%qaq"
      LOG_DIR: /usr/app/log
      LISTEN_IP: developer-be
      SC_ADDRESS: https://${ENV_IP}:30100
      APPSTORE_ADDRESS: https://${ENV_IP}:8099
      POSTGRES_IP: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB_NAME: "developerdb"
      IMAGE_REPO_NAME: ${ENV_IP}
      IMAGE_REPO_PROJECT: "developer"
      IMAGE_REPO_PASSWORD: "Harbor@12345"
      IMAGE_REPO_USERNAME: "admin"
      POSTGRES_USERNAME: "developer"
      POSTGRES_PASSWORD: "te9Fmv%qaq"
      VNC_USERNAME: "ubuntu"
      VNC_PASSWORD: "12345"
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
      SSL_ENABLED: "true"
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: PKCS12
      SSL_KEY_ALIAS: edgegallery
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
      - /var/run/docker.sock:/var/run/docker.sock
