- name: Set multus AMD64 Images
  replace:
    path: "{{ TARBALL_PATH }}/conf/edge/network-isolation/multus.yaml"
    regexp: "image: docker.io/nfvpe/multus:stable$"
    replace: "image: {{mep_images_multus_repository}}:{{mep_images_multus_tag}}"

- name: Set multus ARM64 Images
  replace:
    path: "{{ TARBALL_PATH }}/conf/edge/network-isolation/multus.yaml"
    regexp: "image: docker.io/nfvpe/multus:stable-arm64v8"
    replace: "image: {{mep_images_multus_repository}}:{{mep_images_multus_tag}}"

- name: Set eg-sp-controller Images
  replace:
    path: "{{ TARBALL_PATH }}/conf/edge/network-isolation/eg-sp-controller.yaml"
    regexp: "image: edgegallery/edgegallery-secondary-ep-controller:latest"
    replace: "image: {{mep_images_secondary_ep_controller_repository}}:{{mep_images_secondary_ep_controller_tag}}"

- name: Create Network Isolation Multus Resources
  shell: "kubectl apply -f {{ TARBALL_PATH }}/conf/edge/network-isolation/{{ item }}"
  loop:
    - multus.yaml
    - eg-sp-rbac.yaml
    - eg-sp-controller.yaml

- name: Wait for kube-multus Pod is Ready
  shell: |
    nodes_num=`kubectl get nodes | wc -l`
    ((nodes_num=nodes_num-1))
    multus_num=`kubectl get pods -A | grep "kube-multus" | grep "Running" | wc -l`
    if [ $nodes_num == $multus_num ]; then echo "true"; else echo "false"; fi
  register: multusPodNum
  until: multusPodNum.stdout == "true"
  retries: 30
  delay: 5

- name: Special Network Isolation for Multi Node
  import_tasks: "special_muno_network_isolation.yml"
  when: NODE_MODE == "muno"
