- name: Create Namespace metallb-system
  shell: "kubectl apply -f {{ TARBALL_PATH }}/conf/edge/metallb/namespace.yaml"

- name: Create Secret Memberlist
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

- name: Create Metallb Resources
  shell: "kubectl apply -f {{ TARBALL_PATH }}/conf/edge/metallb/metallb.yaml"

- name: Change Default IP to be the eth0 IP
  replace:
    path: "{{ TARBALL_PATH }}/conf/edge/metallb/config-map.yaml"
    regexp: 192.168.100.120
    replace: "{{ ansible_default_ipv4['address'] }}"

- name: Create ConfigMap
  shell: "kubectl apply -f {{ TARBALL_PATH }}/conf/edge/metallb/config-map.yaml"

- name: Wait for metallb-system controller Pod is Ready
  shell: kubectl get pods -A | grep "metallb-system" | grep "controller-" | grep "Running" | wc -l
  register: controllerPodNum
  until: controllerPodNum.stdout == "1"
  retries: 30
  delay: 5

- name: Wait for metallb-system speaker Pod is Ready
  shell: |
    nodes_num=`kubectl get nodes | wc -l`
    ((nodes_num=nodes_num-1))
    speaker_num=`kubectl get pods -A | grep "metallb-system" | grep "speaker-" | grep "Running" | wc -l`
    if [ $nodes_num == $speaker_num ]; then echo "true"; else echo "false"; fi
  register: speakerPodNum
  until: speakerPodNum.stdout == "true"
  retries: 30
  delay: 5
