#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Set ARCH Value to be amd64
  set_fact:
    ARCH: amd64
  when: ansible_architecture == "x86_64"

- name: Set ARCH Value to be arm64
  set_fact:
    ARCH: arm64
  when: ansible_architecture == "aarch64"

- name: Set Registry URL for Multi Node
  set_fact:
    REGISTRY_URL: "{{ MASTER_IP }}:5000/"
  when: NODE_MODE == "muno"

- name: Set Registry URL for AIO
  set_fact:
    REGISTRY_URL: ""
  when: NODE_MODE == "aio"

- name: Check EG_MODE for MEP
  fail:
    msg: "Could not {{ OPERATION }} MEP with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "edge"

- name: Check whether MEP is Deployed
  shell: helm list -A | grep mep-edgegallery
  register: mepDeployed
  ignore_errors: yes

- debug:
    msg: MEP is already deployed, no need to be deployed again
  when: mepDeployed is succeeded and OPERATION == "install"

- debug:
    msg: MEP is not deployed, will be deployed
  when: mepDeployed is failed and OPERATION == "install"

- debug:
    msg: MEP is already deployed or not deployed successfully, will be undeployed
  when: OPERATION == "uninstall"

- name: Deploy MEP Online
  include: "deploy_online.yml"
  when: mepDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy MEP Offline
  include: "deploy_offline.yml"
  when: mepDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy MEP
  include: "undeploy.yml"
  when: OPERATION == "uninstall" and K8S_NODE_TYPE == "master"

- name: Cleanup MEP Worker Node
  include: "cleanup_worker_node.yml"
  when: OPERATION == "uninstall" and K8S_NODE_TYPE == "worker"
