---
- name: Check whether MEP is Deployed
  shell: helm list | grep mep-edgegallery
  register: mepDeployed
  ignore_errors: yes

- debug:
    msg: MEP is already deployed, no need to be deployed again
  when: mepDeployed is succeeded and OPERATION == "install"

- debug:
    msg: MEP is not deployed, will be deployed
  when: mepDeployed is failed and OPERATION == "install"

- debug:
    msg: MEP is already deployed, will be undeployed
  when: mepDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: MEP is not deployed, no need to be undeployed anymore
  when: mepDeployed is failed and OPERATION == "uninstall"

- name: Deploy MEP Online
  include: "deploy_online.yml"
  when: mepDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy MEP Offline
  include: "deploy_offline.yml"
  when: mepDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy MEP
  include: "undeploy.yml"
  when: mepDeployed is succeeded and OPERATION == "uninstall"
