############################################################################
# Copyright 2021 Huawei Technologies Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

---

- name: Clean EG Docker Images Offline Directory
  file:
    path: "{{ EG_IMAGES_DIR }}"
    state: absent

- name: Create EG Docker Images Offline Directories
  file:
    path: "{{ EG_IMAGES_DIR}}"
    state: directory

- name: Set EG Image List Var for X86 All Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_X86 + EG_IMAGE_LIST_CONTROLLER_X86 + EG_IMAGE_LIST_EDGE_X86}}"
  when: ARCH == "amd64" and EG_MODE == "all"

- name: Set EG Image List Var for X86 Controller Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_X86 + EG_IMAGE_LIST_CONTROLLER_X86 }}"
  when: ARCH == "amd64" and EG_MODE == "controller"

- name: Set EG Image List Var for X86 Edge Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_X86 + EG_IMAGE_LIST_EDGE_X86 }}"
  when: ARCH == "amd64" and EG_MODE == "edge"

- name: Set EG Image List Var for ARM64 All Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_ARM64 + EG_IMAGE_LIST_CONTROLLER_ARM64 + EG_IMAGE_LIST_EDGE_ARM64}}"
  when: ARCH == "arm64" and EG_MODE == "all"

- name: Set EG Image List Var for ARM64 Controller Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_ARM64 + EG_IMAGE_LIST_CONTROLLER_ARM64 }}"
  when: ARCH == "arm64" and EG_MODE == "controller"

- name: Set EG Image List Var for ARM64 Edge Mode
  set_fact:
    eg_image_list: "{{ CLIENT_PROVISIONER_ARM64 + EG_IMAGE_LIST_EDGE_ARM64}}"
  when: ARCH == "arm64" and EG_MODE == "edge"

- name: Set EG Image List Str
  set_fact:
    eg_image_str: "{{ eg_image_list|join(' ') }}"

- name: Pull and Retag All EG Docker Images
  shell: |
    docker pull {{ item }}
    new_image_name=`echo {{ item }} | sed -e "s/swr.ap-southeast-1.myhuaweicloud.com\///g"`
    docker image tag {{ item }} $new_image_name
  loop: "{{ eg_image_list }}"

- name: Save All EG Docker Images Together
  shell: |
    new_image_list=`echo {{ eg_image_str }} | sed -e "s/swr.ap-southeast-1.myhuaweicloud.com\///g"`
    docker save $new_image_list | gzip > {{ EG_IMAGES_DIR }}/eg_images.tar.gz
    echo $new_image_list >> {{ EG_IMAGES_DIR }}/eg_images_list.txt
