version: "3"
services:
    tool-chain:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/tool-chain:latest
        environment:
            LOG_DIR: /var/log/tool-chain
            SC_ADDRESS: http://${ENV_IP}:30100
            LISTEN_IP: ${ENV_IP}
            SSL_ENABLED: "false"
        volumes:
          - /opt/portadv/portadmin:/opt/portadv/portadmin

    porting-advisor:
        image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/porting-advisor:latest
        privileged: true
        volumes:
          - /opt/portadv/portadmin:/opt/portadv/portadmin

    postgres:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3
        environment:
            POSTGRES_USER: "developer"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            POSTGRES_DB: "developerdb"
        volumes:
          - ./postgres-data:/docker-entrypoint-initdb.d/
       
    developer-fe:
       image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-fe:latest
       ports:
         - 30092:8443
       depends_on:
         - postgres
         - tool-chain
         - porting-advisor
       environment:
           LOG_DIR: /var/log/developer-fe
           LOG_FILE_NAME: developer-fe
           LISTEN_IP: ${ENV_IP}
           SC_ADDRESS: http://${ENV_IP}:30100
           AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
           COOKIE_NAME: DEVELOPERSESSIONID
           CLIENT_ID: developer-fe
           CLIENT_SECRET: te9Fmv%qaq
           SSL_ENABLED: "false"
           IS_SECURE_BACKEND: "false"
         
    developer-be:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/developer-be:latest
        depends_on:
          - postgres
          - tool-chain
          - porting-advisor
        environment:
            CLIENT_ID: developer-fe
            CLIENT_SECRET: te9Fmv%qaq
            LOG_DIR: /usr/app/log
            LISTEN_IP: ${ENV_IP}
            SC_ADDRESS: http://${ENV_IP}:30100
            APPSTORE_ADDRESS: http://${ENV_IP}:8099
            POSTGRES_IP: postgres
            POSTGRES_DB_NAME: "developerdb"
            IMAGE_REPO_NAME: ${ENV_IP}
            IMAGE_REPO_PROJECT: "developer"
            IMAGE_REPO_PASSWORD: "Harbor@12345"
            IMAGE_REPO_USERNAME: "admin"
            POSTGRES_USERNAME: "developer"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
            SSL_ENABLED: "false"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
