---

- name: Set Registry URL for Multi Node
  set_fact:
    REGISTRY_URL: "{{ groups.master[0] }}:5000/"
  when: NODE_MODE == "muno"

- name: Set Registry URL for AIO
  set_fact:
    REGISTRY_URL: ""
  when: NODE_MODE == "aio"

- name: Check EG_MODE for MECM-MEPM
  fail:
    msg: "Could not {{ OPERATION }} MECM-MEPM with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "edge"

- name: Check whether MECM-MEPM is Deployed
  shell: helm list | grep mecm-mepm-edgegallery 
  register: mecmMepmDeployed
  ignore_errors: yes

- debug:
    msg: MECM-MEPM is already deployed, no need to be deployed again
  when: mecmMepmDeployed is succeeded and OPERATION == "install"

- debug:
    msg: MECM-MEPM is not deployed, will be deployed
  when: mecmMepmDeployed is failed and OPERATION == "install"

- debug:
    msg: MECM-MEPM is already deployed, will be undeployed
  when: mecmMepmDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: MECM-MEPM is not deployed, no need to be undeployed anymore
  when: mecmMepmDeployed is failed and OPERATION == "uninstall"

- name: Deploy MECM-MEPM Online
  include: "deploy_online.yml"
  when: mecmMepmDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy MECM-MEPM Offline
  include: "deploy_offline.yml"
  when: mecmMepmDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy MECM-MEPM
  include: "undeploy.yml"
  when: mecmMepmDeployed is succeeded and OPERATION == "uninstall"
