#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Copying script to /tmp for execution
  copy:
    src: docker-daemon-update.py
    dest: /tmp/docker-daemon-update.py

- name: Running script docker-daemon-update.py to append daemon.json for amd64
  shell: "python3 /tmp/docker-daemon-update.py {{ groups.master[0] }}:5000 {{ HarborIP }}"
  when: HarborIP is defined

- name: Running script docker-daemon-update.py to append daemon.json for arm64
  shell: "python3 /tmp/docker-daemon-update.py {{ groups.master[0] }}:5000"
  when: HarborIP is undefined

- name: Copy Docker daemon.json From Master Node to Deploy Node
  fetch:
    src: /etc/docker/daemon.json
    dest: "/home"

- name: Restart Docker Service
  service:
    name: docker.service
    state: restarted

- name: Check Whether registry Container Exists
  shell: "docker ps | grep {{ REGISTRY_CONTAINER_NAME }}"
  register: registry_exists
  ignore_errors: yes

- name: Load registry Image
  shell: "docker load --input {{ DOCKER_REGISTRY_IMAGE }}"
  when: registry_exists is failed

- name: Run registry Container
  shell: "docker run -d -p 5000:5000 --restart=always --name {{ REGISTRY_CONTAINER_NAME }} {{ REGISTRY_IMAGE_NAME }}"
  when: registry_exists is failed
