#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Check Whether /etc/docker/daemon.json Exists
  stat:
    path: /etc/docker/daemon.json
  register: file_status

- name: Appending daemon.json file with aio-daemon.json contents, when daemon.json exists
  blockinfile:
    block: "{{ lookup('file', 'aio-daemon.json') }}"
    path: /etc/docker/daemon.json
  when: file_status.stat.exists == True

- name: Create File /etc/docker/daemon.json, when it does not exist
  copy:
    src: aio-daemon.json
    dest: /etc/docker/daemon.json
  when: file_status.stat.exists == False

- name: Set insecure-registries IP in /etc/docker/daemon.json
  replace:
    path: /etc/docker/daemon.json
    regexp: PRIVATE_HARBOR_IP
    replace: "{{ HarborIP }}"
  when: file_status.stat.exists == False

- name: Restart Docker Service
  service:
    name: docker.service
    state: restarted
  when: file_status.stat.exists == False
