#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Copy k8s-worker.sh From Deploy Node to Worker Node
  copy:
    src: "/home/{{ MASTER_IP }}{{ K8S_OFFLINE_DIR }}/k8s-worker.sh"
    dest: "{{K8S_OFFLINE_DIR}}/k8s-worker.sh"

- name: Create ~/.kube Directory on Worker Node
  file:
    path: "/root/.kube/"
    state: directory

- name: Copy kube config From Deploy Node to Worker Node
  copy:
    src: "/home/{{ MASTER_IP }}/root/.kube/config"
    dest: "/root/.kube/"

- name: Execute File k8s-worker.sh
  shell: "bash {{K8S_OFFLINE_DIR}}/k8s-worker.sh"
