- name: Install k8s with kubeadm
  shell: "kubeadm init --kubernetes-version=v1.18.7 --apiserver-advertise-address={{ansible_default_ipv4['address']}} --pod-network-cidr=10.244.0.0/16 -v=5"

- name: Create the Directory for Kube Config
  file:
    path: ~/.kube
    state: directory

- name: Copy K8s admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes

- name: Apply calico
  shell: "kubectl apply -f {{K8S_OFFLINE_DIR}}/k8s/calico.yaml"

- name: Set K8s Taint Nodes
  shell: "kubectl taint nodes --all node-role.kubernetes.io/master-"

- name: Create Kubeadm Token
  shell: "kubeadm token create --print-join-command > {{K8S_OFFLINE_DIR}}/k8s-worker.sh"

- name: Copy k8s-worker.sh to Deploy Node
  fetch:
    src: "{{ item }}"
    dest: "/home/"
  loop:
    - "{{ K8S_OFFLINE_DIR }}/k8s-worker.sh"
    - "/root/.kube/config"

- name: K8s Apply Metric Server
  shell: "kubectl apply -f {{ K8S_OFFLINE_DIR }}/k8s/metric-server.yaml"
