---

- name: Copy k8s-worker.sh From Deploy Node to Worker Node
  copy:
    src: "/home/{{ groups.master[0] }}{{ K8S_OFFLINE_DIR }}/k8s-worker.sh"
    dest: "{{K8S_OFFLINE_DIR}}/k8s-worker.sh"

- name: Create ~/.kube Directory on Worker Node
  file:
    path: "/root/.kube/"
    state: directory

- name: Copy kube config From Deploy Node to Worker Node
  copy:
    src: "/home/{{ groups.master[0] }}/root/.kube/config"
    dest: "/root/.kube/"

- name: Execute File k8s-worker.sh
  shell: "bash {{K8S_OFFLINE_DIR}}/k8s-worker.sh"
