#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Install Harbor on Master Node
  include: "install_harbor.yml"
  when: ((PORTAL_IP is defined and HarborIP == PORTAL_IP) or HarborIP == MASTER_IP) and ARCH == "amd64"

- name: Docker Login Harbor
  shell: docker login -u admin -p {{ HARBOR_ADMIN_PASSWORD }} {{ HarborIP }}
  register: harborLogin
  until: harborLogin is succeeded
  retries: 12
  delay: 5
  no_log: true
  ignore_errors: yes

- name: Output of "Docker Login Harbor" task
  debug:
    msg: "rc: {{harborLogin.rc}}, stderr: {{harborLogin.stderr}}, stderr_lines: {{harborLogin.stderr_lines}}, stdout: {{harborLogin.stdout}}, stdout_lines: {{harborLogin.stdout_lines}}"
  when: harborLogin is failed

- name: Failing as task "Docker Login Harbor" failed
  fail:
    msg: The task Docker Login Harbor has failed
  when: harborLogin is failed

- name: Check Whether appstore Project Already Exists
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects?project_name=appstore"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: HEAD
    validate_certs: no
    force_basic_auth: yes
    headers:
      Accept: application/json
  register: getAppstoreProject
  ignore_errors: yes

- name: Create appstore Project
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    headers:
      Content-Type: application/json
      Accept: application/json
    body_format: json
    body: {"project_name":"appstore","metadata":{"public":"true"}}
    status_code: 201
  when: getAppstoreProject.status != 200

- name: Check Whether developer Project Already Exists
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects?project_name=developer"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: HEAD
    validate_certs: no
    force_basic_auth: yes
    headers:
      Accept: application/json
  register: getDeveloperProject
  ignore_errors: yes

- name: Create developer Project
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    headers:
      Content-Type: application/json
      Accept: application/json
    body_format: json
    body: {"project_name":"developer","metadata":{"public":"true"}}
    status_code: 201
  when: getDeveloperProject.status != 200

- name: Check Whether mecm Project Already Exists
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects?project_name=mecm"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: HEAD
    validate_certs: no
    force_basic_auth: yes
    headers:
      Accept: application/json
  register: getMecmProject
  ignore_errors: yes

- name: Create mecm Project
  uri:
    url: "https://{{ HarborIP }}/api/v2.0/projects"
    user: admin
    password: "{{ HARBOR_ADMIN_PASSWORD }}"
    method: POST
    validate_certs: no
    force_basic_auth: yes
    headers:
      Content-Type: application/json
      Accept: application/json
    body_format: json
    body: {"project_name":"mecm","metadata":{"public":"true"}}
    status_code: 201
  when: getMecmProject.status != 200

- name: Create docker-registry Secret For Harbor
  shell: kubectl create secret docker-registry harbor --docker-server=https://{{ HarborIP }} --docker-username=admin --docker-password={{ HARBOR_ADMIN_PASSWORD }}
  no_log: true
  ignore_errors: yes
  register: harbor_secret

- name: Output of "Create docker-registry Secret For Harbor" task
  debug:
    msg: "rc: {{harbor_secret.rc}}, stderr: {{harbor_secret.stderr}}, stderr_lines: {{harbor_secret.stderr_lines}}, stdout: {{harbor_secret.stdout}}, stdout_lines: {{harbor_secret.stdout_lines}}"
  when: harbor_secret is failed

- name: Failing as task "Create docker-registry Secret For Harbor" failed
  fail:
    msg: The task Create docker-registry Secret For Harbor has failed
  when: harbor_secret is failed

- name: Add Harbor Secret to Default serviceaccount
  shell: >
    kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "harbor"}]}'
