---

- name: Create SSL Certs
  shell: "docker run --rm -e CERT_VALIDITY_IN_DAYS={{ CERT_VALIDITY_IN_DAYS }} -v {{ TARBALL_PATH }}/conf/keys/:/certs edgegallery/deploy-tool:{{ EG_IMAGE_TAG }}"

- name: Create Secret edgegallery-ssl-secret
  shell: |
    kubectl create secret generic edgegallery-ssl-secret \
      --from-file=keystore.p12={{ TARBALL_PATH }}/conf/keys/keystore.p12 \
      --from-literal=keystorePassword={{ keystorePassword }} \
      --from-literal=keystoreType={{ keystoreType }} \
      --from-literal=keyAlias={{ keyAlias }} \
      --from-file=trust.cer={{ TARBALL_PATH }}/conf/keys/ca.crt \
      --from-file=server.cer={{ TARBALL_PATH }}/conf/keys/tls.crt \
      --from-file=server_key.pem={{ TARBALL_PATH }}/conf/keys/encryptedtls.key \
      --from-literal=cert_pwd={{ cert_pwd }}
  when: EG_MODE == "all" or EG_MODE == "controller"

- name: Install Service Center
  shell: |
    helm install --wait service-center-edgegallery {{ HELM_CHARTS_PATH }}/edgegallery/servicecenter-{{ HELM_TAG }}.tgz \
    --set images.repository={{ servicecenter_images_repository }} \
    --set images.pullPolicy={{ servicecenter_images_pullPolicy }} \
    --set global.ssl.enabled={{ servicecenter_global_ssl_enabled }} \
    --set global.ssl.secretName={{ servicecenter_global_ssl_secretName }}
  when: EG_MODE == "all" or EG_MODE == "controller"
