version: "3"
services:
  mecm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-fe:v1.1.1
    ports: 
      - 30093:8443
    depends_on: 
      - postgres
    environment:
      LOG_DIR: /var/log/mecm-fe
      LOG_FILE_NAME: "mecm-fe"
      LISTEN_IP: mecm-fe
      SC_ADDRESS: https://${ENV_IP}:30100
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
      COOKIE_NAME: MECMSESSIONID
      CLIENT_ID: "mecm-fe"
      CLIENT_SECRET: "te9Fmv%qaq"
      SSL_ENABLED: "true"
      IS_SECURE_BACKEND: "true"
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: "PKCS12"
      SSL_KEY_ALIAS: "edgegallery"
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12

  appo:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appo:v1.1.1
    ports:
      - 8091:8091
    depends_on:
      - postgres
    environment:
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      SC_ADDRESS: https://${ENV_IP}:30100
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_TRUST_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: "PKCS12"
      SSL_KEY_ALIAS: "edgegallery"
      SSL_KEY_STORE_JKS_PATH: /usr/app/ssl/keystore.jks
      APPO_DB_PASSWORD: "te9Fmv%qaq"
      APPO_DB_HOST: ${ENV_IP}
      APPO_DB_PORT: 8094
      SSL_ENABLED: "true"
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
      - /tmp/keys/keystore.jks:/usr/app/ssl/keystore.jks

  apm:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apm:v1.1.1
    ports:
      - 8092:8092
    depends_on:
      - postgres
    environment:
      LOG_DIR: /usr/app/log
      PUSH_IMAGE: "false"
      LISTEN_IP: ${ENV_IP}
      SC_ADDRESS: https://${ENV_IP}:30100
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_TRUST_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: "PKCS12"
      SSL_KEY_ALIAS: "edgegallery"
      SSL_KEY_STORE_JKS_PATH: /usr/app/ssl/keystore.jks
      APM_DB_PASSWORD: "te9Fmv%qaq"
      APM_DB_HOST: ${ENV_IP}
      APM_DB_PORT: 8094
      MECM_REPO_PASSWORD: "Harbor@12345"
      MECM_REPO_USERNAME: "admin"
      MECM_REPO_ENDPOINT: ${ENV_IP}
      SSL_ENABLED: "true"
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
      - /tmp/keys/keystore.jks:/usr/app/ssl/keystore.jks

  inventory:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-inventory:v1.1.1
    ports:
      - 8093:8093
    depends_on:
      - postgres 
    environment: 
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      SC_ADDRESS: https://${ENV_IP}:30100
      SSL_KEY_STORE_PATH: /usr/app/ssl/keystore.p12
      SSL_KEY_STORE_PASSWORD: "te9Fmv%qaq"
      SSL_TRUST_PASSWORD: "te9Fmv%qaq"
      SSL_KEY_STORE_TYPE: "PKCS12"
      SSL_KEY_ALIAS: "edgegallery"
      SSL_KEY_STORE_JKS_PATH: /usr/app/ssl/keystore.jks
      INVENTORY_DB_PASSWORD: "te9Fmv%qaq"
      INVENTORY_DB_HOST: ${ENV_IP}
      INVENTORY_DB_PORT: 8094
      SOURCE_REPOS: repo=${ENV_IP} userName=admin password=Harbor@12345
      SSL_ENABLED: "true"
      AUTH_SERVER_ADDRESS: https://${ENV_IP}:30067
    volumes:
      - /tmp/keys/keystore.p12:/usr/app/ssl/keystore.p12
      - /tmp/keys/keystore.jks:/usr/app/ssl/keystore.jks

  postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3
    ports:
      - 8094:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "te9Fmv%qaq"
      POSTGRES_DB: "root"
    volumes:
      - ./postgres-data:/docker-entrypoint-initdb.d/
