version: "3"
services:
　mecm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-fe:v1.1.1
    ports:
    　- 30093:8443
    depends_on:
    　- postgres
    environment:
      LOG_DIR: /var/log/mecm-fe
      LOG_FILE_NAME: mecm-fe    
      LISTEN_IP: ${ENV_IP}
      fieldPath: status.podIP
      SC_ADDRESS: http://${ENV_IP}:30100
      AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
      COOKIE_NAME: MECMSESSIONID
      CLIENT_ID: mecm-fe
      CLIENT_SECRET: te9Fmv%qaq
      SSL_ENABLED: "false"
      CLIENT_ID: bWVjbS1mZQ==
      
　inventory:
　　image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-inventory:v1.1.1
		ports:
  　　- 30203:8093
		depends_on:
  　　- postgres 
  　environment:
  　　LOG_DIR: /usr/app/log
			LOG_FILE_NAME: inventory-log
			LISTEN_IP: ${ENV_IP}
			SC_ADDRESS: http://${ENV_IP}:30100
　　　COOKIE_NAME: MECMSTORESESSIONID
　　　CLIENT_ID: mecm
　　　CLIENT_SECRET: te9Fmv%qaq
　　　SSL_ENABLED: "false"
　　　IS_SECURE_BACKEND: "false"
        
　appo:
　　image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appo:v1.1.1
　　ports:
　　　- 30201:8091
    depends_on:
    　- postgres
　　environment:
　　　LOG_DIR: /usr/app/log
　　　LOG_FILE_NAME: appo-log
　　　LISTEN_IP:appstore_appstore-be_1  ${ENV_IP}
　　　SC_ADDRESS: http://${ENV_IP}:30100
　　　AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
　　　COOKIE_NAME: MECMSTORESESSIONID
　　　CLIENT_ID: mecm
　　　CLIENT_SECRET: te9Fmv%qaq
　　　SSL_ENABLED: "false"
　　　IS_SECURE_BACKEND: "false"
		   
　apm:
　　image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apm:v1.1.1
		ports:
  　　- 30202:8092
　　depends_on:
　　　- postgres
　　environment:
　　　LOG_DIR: /usr/app/log
　　　LISTEN_IP: ${ENV_IP}
　　　SC_ADDRESS: http://${ENV_IP}:30100
　　　COOKIE_NAME: MECMSTORESESSIONID
　　　CLIENT_ID: mecm
　　　CLIENT_SECRET: te9Fmv%qaq
　　　SSL_ENABLED: "false"
         

    postgres:
        image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/postgres:12.3
        environment:
            CLIENT_ID: appstore-be
            CLIENT_SECRET: te9Fmv%qaq
            LOG_DIR: /usr/app/log
            LISTEN_IP: ${ENV_IP}
            SC_ADDRESS: http://${ENV_IP}:30100
            APPSTORE_ADDRESS: http://${ENV_IP}:8099
            POSTGRES_IP: postgres
            POSTGRES_DB_NAME: "POSTGRES_DB"
            IMAGE_REPO_NAME: ${ENV_IP}
            POSTGRES_USERNAME: "mecm"
            POSTGRES_PASSWORD: "te9Fmv%qaq"
            AUTH_SERVER_ADDRESS: http://${ENV_IP}:30067
            SSL_ENABLED: "false"
        volumes:
          - ./postgres-data:/docker-entrypoint-initdb.d/