#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Deploy file-system
  shell: |
    helm install --wait file-system-edgegallery {{ HELM_CHARTS_PATH }}/edgegallery/filesystem-{{ HELM_TAG }}.tgz \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set images.filesystem.repository={{ filesystem_images_repository }} \
    --set images.filesystem.tag={{ EG_IMAGE_TAG }} \
    --set images.filesystem.pullPolicy={{ filesystem_images_pullPolicy }} \
    --set images.imageops.repository={{ imageops_images_repository }} \
    --set images.imageops.tag={{ EG_IMAGE_TAG }} \
    --set images.imageops.pullPolicy={{ imageops_images_pullPolicy }} \
    --set images.postgres.repository={{ filesystem_postgres_images_repository }} \
    --set images.postgres.tag={{ filesystem_postgres_images_tag }} \
    --set images.postgres.pullPolicy={{ filesystem_postgres_images_pullPolicy }} \
    --set filesystem.hostVMImagePath={{ FILE_SYSTEM_PACKAGES }} \
    --set postgres.password={{ postgresPassword }}
