#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Deploy ATP
  shell: |
    helm install --wait {{ ATP_HELM_RELEASE_NAME }} {{ HELM_CHARTS_PATH }}/edgegallery/atp-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress=https://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }} \
    --set global.oauth2.authServerAddressClientAccess={{ AUTH_SERVER_ADDRESS_CLIENT_ACCESS }} \
    --set global.oauth2.redirectUriParam={{ ATP_REDIRECT_URI_PARAM }} \
    --set global.oauth2.clients.atp.clientSecret={{ oauth2ClientPassword }} \
    --set images.atpFe.repository={{ atp_images_atpFe_repository }} \
    --set images.atp.repository={{ atp_images_atp_repository }} \
    --set images.postgres.repository={{ atp_images_postgres_repository }} \
    --set images.initservicecenter.repository={{ atp_images_initservicecenter_repository }} \
    --set images.atpFe.tag={{ atp_images_atpFe_tag }} \
    --set images.atp.tag={{ atp_images_atp_tag }} \
    --set images.postgres.tag={{ atp_images_postgres_tag }} \
    --set images.initservicecenter.tag={{ atp_images_curl_tag }} \
    --set images.atpFe.pullPolicy={{ atp_images_atpFe_pullPolicy }} \
    --set images.atp.pullPolicy={{ atp_images_atp_pullPolicy }} \
    --set images.postgres.pullPolicy={{ atp_images_postgres_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ atp_images_initservicecenter_pullPolicy }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set global.ssl.enabled={{ ENABLE_SSL }} \
    --set global.ssl.secretName={{ atp_global_ssl_secretName }} \
    --set postgres.password={{ postgresPassword }}
  no_log: true
  ignore_errors: yes
  register: atp_out

- name: Output of "Deploy ATP" task
  debug:
    msg: "rc: {{atp_out.rc}}, stderr: {{atp_out.stderr}}, stderr_lines: {{atp_out.stderr_lines}}, stdout: {{atp_out.stdout}}, stdout_lines: {{atp_out.stdout_lines}}"
  when: atp_out is failed

- name: Failing as task "Deploy ATP" failed
  fail:
    msg: The task Deploy ATP has failed
  when: atp_out is failed

- name: Check ATP Status
  uri:
    url: "https://{{ PORTAL_IP }}:{{ item }}/health"
    validate_certs: no
  loop:
    - 30094
