---

- name: Check EG_MODE for ATP
  fail:
    msg: "Could not {{ OPERATION }} ATP with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "controller"

- name: Set Portal IP
  set_fact:
    PORTAL_IP: "{{ ansible_default_ipv4['address'] }}"
  when: PORTAL_IP is undefined

- name: Check whether ATP is Deployed
  shell: "helm list | grep {{ ATP_HELM_RELEASE_NAME }}"
  register: atpDeployed 
  ignore_errors: yes

- debug:
    msg: ATP is already deployed, no need to be deployed again
  when: atpDeployed is succeeded and OPERATION == "install"

- debug:
    msg: ATP is not deployed, will be deployed
  when: atpDeployed is failed and OPERATION == "install"

- debug:
    msg: ATP is already deployed, will be undeployed
  when: atpDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: ATP is not deployed, no need to be undeployed anymore
  when: atpDeployed is failed and OPERATION == "uninstall"

- name: Deploy ATP Online
  include: "deploy_online.yml"
  when: atpDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy ATP Offline
  include: "deploy_offline.yml"
  when: atpDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy ATP
  include: "undeploy.yml"
  when: atpDeployed is succeeded and OPERATION == "uninstall"
