#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Set Registry URL for Multi Node
  set_fact:
    REGISTRY_URL: "{{ groups.master[0] }}:5000/"
  when: NODE_MODE == "muno"

- name: Set Registry URL for AIO
  set_fact:
    REGISTRY_URL: ""
  when: NODE_MODE == "aio"

- name: Check EG_MODE for ATP
  fail:
    msg: "Could not {{ OPERATION }} ATP with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "controller"

- name: Set Portal IP
  set_fact:
    PORTAL_IP: "{{ ansible_default_ipv4['address'] }}"
  when: PORTAL_IP is undefined

- name: Check whether ATP is Deployed
  shell: "helm list | grep {{ ATP_HELM_RELEASE_NAME }}"
  register: atpDeployed 
  ignore_errors: yes

- debug:
    msg: ATP is already deployed, no need to be deployed again
  when: atpDeployed is succeeded and OPERATION == "install"

- debug:
    msg: ATP is not deployed, will be deployed
  when: atpDeployed is failed and OPERATION == "install"

- debug:
    msg: ATP is already deployed, will be undeployed
  when: atpDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: ATP is not deployed, no need to be undeployed anymore
  when: atpDeployed is failed and OPERATION == "uninstall"

- name: Deploy ATP Online
  include: "deploy_online.yml"
  when: atpDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy ATP Offline
  include: "deploy_offline.yml"
  when: atpDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy ATP
  include: "undeploy.yml"
  when: atpDeployed is succeeded and OPERATION == "uninstall"
