#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---
- name: Set Harbor IP to HarborIP
  set_fact:
    HarborIP: "{{ HarborIP }}"
  when: HarborIP is defined and HarborIP is not none

- name: Set Harbor IP to PORTAL IP on amd64
  set_fact:
    HarborIP: "{{ PORTAL_IP }}"
  when: ARCH == "amd64" and PORTAL_IP is defined and K8S_NODE_TYPE == "master" and (HarborIP is undefined or HarborIP is none)

- name: Deploy APPSTORE
  shell: |
    helm install --wait {{ APPSTORE_HELM_RELEASE_NAME }} {{ HELM_CHARTS_PATH }}/edgegallery/appstore-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress=https://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }} \
    --set global.oauth2.clients.appstore.clientSecret={{ oauth2ClientPassword }} \
    --set images.appstoreFe.repository={{ appstore_images_appstoreFe_repository }} \
    --set images.appstoreBe.repository={{ appstore_images_appstoreBe_repository }} \
    --set images.postgres.repository={{ appstore_images_postgres_repository }} \
    --set images.initservicecenter.repository={{ appstore_images_initservicecenter_repository }} \
    --set images.appstoreFe.tag={{ appstore_images_appstoreFe_tag }} \
    --set images.appstoreBe.tag={{ appstore_images_appstoreBe_tag }} \
    --set images.postgres.tag={{ appstore_images_postgres_tag }} \
    --set images.initservicecenter.tag={{ appstore_images_initservicecenter_tag }} \
    --set images.appstoreFe.pullPolicy={{ appstore_images_appstoreFe_pullPolicy }} \
    --set images.appstoreBe.pullPolicy={{ appstore_images_appstoreBe_pullPolicy }} \
    --set images.postgres.pullPolicy={{ appstore_images_postgres_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ appstore_images_initservicecenter_pullPolicy }} \
    --set global.ssl.enabled={{ appstore_global_ssl_enabled }} \
    --set global.ssl.secretName={{ appstore_global_ssl_secretName }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set appShare.platformUrl=https://{{ PORTAL_IP }}:30099 \
    --set appShare.atpReportUrl=https://{{ PORTAL_IP }}:30094/#/atpreport?taskid=%s \
    --set appstoreBe.secretName={{ SIGNATURE_SECRET_NAME }} \
    --set appstoreBe.dockerRepo.endpoint={{ HarborIP }} \
    --set appstoreBe.dockerRepo.appstore.password={{ HARBOR_ADMIN_PASSWORD }} \
    --set appstoreBe.dockerRepo.appstore.username=admin \
    --set appstoreBe.dockerRepo.developer.password={{ HARBOR_ADMIN_PASSWORD }} \
    --set appstoreBe.dockerRepo.developer.username=admin \
    --set appstoreBe.hostPackagesPath={{ APPSTORE_PACKAGES }} \
    --set postgres.password={{ postgresPassword }}
  no_log: true
  ignore_errors: true
  register: appstore_out

- name: Output of "Deploy APPSTORE" task
  debug:
    msg: "rc: {{appstore_out.rc}}, stderr: {{appstore_out.stderr}}, stderr_lines: {{appstore_out.stderr_lines}}, stdout: {{appstore_out.stdout}}, stdout_lines: {{appstore_out.stdout_lines}}"
  when: appstore_out is failed

- name: Failing as task "Deploy APPSTORE" failed
  fail:
    msg: The task Deploy APPSTORE has failed
  when: appstore_out is failed

- name: Check APPSTORE Status
  uri:
    url: "https://{{ PORTAL_IP }}:{{ item }}/health"
    validate_certs: no
  loop:
    - 30091
    - 30099
