#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Create Secret edgegallery-appstore-docker-secret
  shell: |
    kubectl create secret generic edgegallery-appstore-docker-secret \
      --from-literal=devRepoUserName=admin \
      --from-literal=devRepoPassword={{ HARBOR_ADMIN_PASSWORD }} \
      --from-literal=appstoreRepoUserName=admin \
      --from-literal=appstoreRepoPassword={{ HARBOR_ADMIN_PASSWORD }}

- name: Deploy APPSTORE
  shell: |
    helm install --wait {{ APPSTORE_HELM_RELEASE_NAME }} {{ HELM_CHARTS_PATH }}/edgegallery/appstore-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress=https://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }} \
    --set images.appstoreFe.repository={{ appstore_images_appstoreFe_repository }} \
    --set images.appstoreBe.repository={{ appstore_images_appstoreBe_repository }} \
    --set images.postgres.repository={{ appstore_images_postgres_repository }} \
    --set images.initservicecenter.repository={{ appstore_images_initservicecenter_repository }} \
    --set images.appstoreFe.tag={{ appstore_images_appstoreFe_tag }} \
    --set images.appstoreBe.tag={{ appstore_images_appstoreBe_tag }} \
    --set images.postgres.tag={{ appstore_images_postgres_tag }} \
    --set images.initservicecenter.tag={{ appstore_images_initservicecenter_tag }} \
    --set images.appstoreFe.pullPolicy={{ appstore_images_appstoreFe_pullPolicy }} \
    --set images.appstoreBe.pullPolicy={{ appstore_images_appstoreBe_pullPolicy }} \
    --set images.postgres.pullPolicy={{ appstore_images_postgres_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ appstore_images_initservicecenter_pullPolicy }} \
    --set global.ssl.enabled={{ appstore_global_ssl_enabled }} \
    --set global.ssl.secretName={{ appstore_global_ssl_secretName }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set poke.platformUrl={{ appstore_poke_platformUrl }} \
    --set poke.atpReportUrl={{ appstore_poke_atpReportUrl }} \
    --set appstoreBe.repository.dockerRepoEndpoint={{ ansible_default_ipv4['address'] }} \
    --set appstoreBe.secretName=edgegallery-appstore-docker-secret

- name: Check APPSTORE Status
  uri:
    url: "https://{{ ansible_default_ipv4['address'] }}:{{ item }}/health"
    validate_certs: no
  loop:
    - 30091
    - 30099
