---

- name: Set Registry URL for Multi Node
  set_fact:
    REGISTRY_URL: "{{ groups.master[0] }}:5000/"
  when: NODE_MODE == "muno"

- name: Set Registry URL for AIO
  set_fact:
    REGISTRY_URL: ""
  when: NODE_MODE == "aio"

- name: Check EG_MODE for APPSTORE
  fail:
    msg: "Could not {{ OPERATION }} APPSTORE with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "controller"

- name: Set Portal IP
  set_fact:
    PORTAL_IP: "{{ ansible_default_ipv4['address'] }}"
  when: PORTAL_IP is undefined

- name: Check whether APPSTORE is Deployed
  shell: "helm list -A | grep {{ APPSTORE_HELM_RELEASE_NAME }}"
  register: appstoreDeployed 
  ignore_errors: yes

- debug:
    msg: APPSTORE is already deployed, no need to be deployed again
  when: appstoreDeployed is succeeded and OPERATION == "install"

- debug:
    msg: APPSTORE is not deployed, will be deployed
  when: appstoreDeployed is failed and OPERATION == "install"

- debug:
    msg: APPSTORE is already deployed, will be undeployed
  when: appstoreDeployed is succeeded and OPERATION == "uninstall"

- debug:
    msg: APPSTORE is not deployed, no need to be undeployed anymore
  when: appstoreDeployed is failed and OPERATION == "uninstall"

- name: Deploy APPSTORE Online
  include: "deploy_online.yml"
  when: appstoreDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy APPSTORE Offline
  include: "deploy_offline.yml"
  when: appstoreDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy APPSTORE
  include: "undeploy.yml"
  when: appstoreDeployed is succeeded and OPERATION == "uninstall"
