#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Check HARBOR_ADMIN_PASSWORD Param
  fail:
    msg: "Param HARBOR_ADMIN_PASSWORD in var.yml is not defined"
  when: HARBOR_ADMIN_PASSWORD is undefined or HARBOR_ADMIN_PASSWORD is none and OPERATION == "install"

- name: Set Portal IP
  set_fact:
    PORTAL_IP: "{{ groups.master[0] }}"
  when: PORTAL_IP is undefined

- name: Check USER_MGMT Status
  uri:
    url: "https://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }}/health"
    validate_certs: no
  register: user_mgmt_interacts
  when: OPERATION == "install"
  ignore_errors: yes

- name: Failing the Installation as 'user-mgmt' deployement needs to be completed before 'appstore'
  fail:
    msg: "'user_mgmt' is not reachable, complete user_mgmt deployment before 'appstore'"
  when: user_mgmt_interacts is failed and OPERATION == "install"

- name: Set Registry URL for Multi Node
  set_fact:
    REGISTRY_URL: "{{ groups.master[0] }}:5000/"
  when: NODE_MODE == "muno"

- name: Set Registry URL for AIO
  set_fact:
    REGISTRY_URL: ""
  when: NODE_MODE == "aio"

- name: Check EG_MODE for APPSTORE
  fail:
    msg: "Could not {{ OPERATION }} APPSTORE with EG_MODE: {{ EG_MODE }}"
  when: EG_MODE != "all" and EG_MODE != "controller"

- name: Check whether APPSTORE is Deployed
  shell: "helm list -A | grep {{ APPSTORE_HELM_RELEASE_NAME }}"
  register: appstoreDeployed 
  ignore_errors: yes

- debug:
    msg: APPSTORE is already deployed, no need to be deployed again
  when: appstoreDeployed is succeeded and OPERATION == "install"

- debug:
    msg: APPSTORE is not deployed, will be deployed
  when: appstoreDeployed is failed and OPERATION == "install"

- debug:
    msg: APPSTORE is already deployed or not deployed successfully, will be undeployed
  when: OPERATION == "uninstall"

- name: Deploy APPSTORE Online
  include: "deploy_online.yml"
  when: appstoreDeployed is failed and OPERATION == "install" and NETWORK_MODE == "online"

- name: Deploy APPSTORE Offline
  include: "deploy_offline.yml"
  when: appstoreDeployed is failed and OPERATION == "install" and NETWORK_MODE == "offline"

- name: Undeploy APPSTORE
  include: "undeploy.yml"
  when: OPERATION == "uninstall"
