#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Create Secret eg-view-ssl-secret
  shell: |
    kubectl create secret generic {{ egView_ssl_secretName }} \
      --from-file=server.crt={{ TARBALL_PATH }}/conf/keys/server.crt \
      --from-file=server.key={{ TARBALL_PATH }}/conf/keys/server.key
  no_log: true
  ignore_errors: yes
  register: egview_secret_out

- name: Output of "Create Secret eg-view-ssl-secret" task
  debug:
    msg: "rc: {{egview_secret_out.rc}}, stderr: {{egview_secret_out.stderr}}, stderr_lines: {{egview_secret_out.stderr_lines}}, stdout: {{egview_secret_out.stdout}}, stdout_lines: {{egview_secret_out.stdout_lines}}"
  when: egview_secret_out is failed

- name: Failing as task "Create Secret eg-view-ssl-secret" failed
  fail:
    msg: The task Create Secret eg-view-ssl-secret has failed
  when: egview_secret_out is failed

- name: Deploy EG-VIEW
  shell: |
    helm install --wait {{ EG_VIEW_HELM_RELEASE_NAME }} {{ HELM_CHARTS_PATH }}/edgegallery/eg-view-{{ HELM_TAG }}.tgz \
    --set ssl.secretName={{ egView_ssl_secretName }} \
    --set images.egView.repository={{ egView_images_repository }} \
    --set images.egView.tag={{ egView_images_tag }} \
    --set images.egView.pullPolicy={{ egView_images_pullPolicy }}

- name: Create Secret developer-ssl-secret
  shell: |
    kubectl create secret generic {{ developer_ssl_certName }} \
      --from-file=server.crt={{ TARBALL_PATH }}/conf/keys/server.crt \
      --from-file=server.key={{ TARBALL_PATH }}/conf/keys/server.key
  no_log: true
  ignore_errors: yes
  register: developer_secret_out
  
- name: Output of "Create Secret developer-ssl-secret" task
  debug:
    msg: "rc: {{developer_secret_out.rc}}, stderr: {{developer_secret_out.stderr}}, stderr_lines: {{developer_secret_out.stderr_lines}}, stdout: {{developer_secret_out.stdout}}, stdout_lines: {{developer_secret_out.stdout_lines}}"
  when: developer_secret_out is failed

- name: Failing as task "Create Secret developer-ssl-secret" failed
  fail:
    msg: The task Create Secret developer-ssl-secret has failed
  when: developer_secret_out is failed

- name: Deploy DEVELOPER
  shell: |
    helm install --wait {{ DEVELOPER_HELM_RELEASE_NAME }} {{ HELM_CHARTS_PATH }}/edgegallery/developer-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress={{ PROTOCOL }}://{{ PORTAL_IP }}:{{ USER_MGMT_PORT }} \
    --set global.oauth2.authServerAddressClientAccess={{ AUTH_SERVER_ADDRESS_CLIENT_ACCESS }} \
    --set global.oauth2.redirectUriParam={{ DEVELOPER_REDIRECT_URI_PARAM }} \
    --set global.oauth2.clients.developer.clientSecret={{ oauth2ClientPassword }} \
    --set images.developerFe.repository={{ developer_images_developerFe_repository }} \
    --set images.developerBe.repository={{ developer_images_developerBe_repository }} \
    --set images.commonServiceCbb.repository={{ developer_images_commoncbb_repository }} \
    --set images.postgres.repository={{ developer_images_postgres_repository }} \
    --set images.initservicecenter.repository={{ developer_images_initservicecenter_repository }} \
    --set images.developerFe.tag={{ developer_images_developerFe_tag }} \
    --set images.developerBe.tag={{ developer_images_developerBe_tag }} \
    --set images.commonServiceCbb.tag={{ developer_images_commoncbb_tag }} \    
    --set images.postgres.tag={{ developer_images_postgres_tag }} \
    --set images.initservicecenter.tag={{ developer_images_initservicecenter_tag }} \
    --set images.developerFe.pullPolicy={{ developer_images_developerFe_pullPolicy }} \
    --set images.developerBe.pullPolicy={{ developer_images_developerBe_pullPolicy }} \
    --set images.commonServiceCbb.pullPolicy={{ developer_images_commoncbb_pullPolicy }} \
    --set images.postgres.pullPolicy={{ developer_images_postgres_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ developer_images_initservicecenter_pullPolicy }} \
    --set global.ssl.enabled={{ ENABLE_SSL }} \
    --set global.ssl.secretName={{ developer_global_ssl_secretName }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }} \
    --set developer.ssl.certName={{ developer_ssl_certName }} \
    --set developer.dockerRepo.endpoint={{ HarborIP }} \
    --set developer.dockerRepo.password={{ HARBOR_ADMIN_PASSWORD }} \
    --set developer.dockerRepo.username=admin \
    --set postgres.password={{ postgresPassword }} \
    --set developer.developerBeIp={{ PORTAL_IP }} \
    --set developer.vmImage.fileSystemAddress=http://{{ PORTAL_IP }}:30090 \
    --set developer.toolChain.enabled={{ toolchain_enabled }}
  no_log: true
  ignore_errors: yes
  register: developer_out

- name: Output of "Deploy DEVELOPER" task
  debug:
    msg: "rc: {{developer_out.rc}}, stderr: {{developer_out.stderr}}, stderr_lines: {{developer_out.stderr_lines}}, stdout: {{developer_out.stdout}}, stdout_lines: {{developer_out.stdout_lines}}"
  when: developer_out is failed

- name: Failing as task "Deploy DEVELOPER" failed
  fail:
    msg: The task Deploy DEVELOPER has failed
  when: developer_out is failed

- name: Check DEVELOPER Status
  uri:
    url: "{{ PROTOCOL }}://{{ PORTAL_IP }}:30092/health"
    validate_certs: no
