# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Copy k3s nodeToken From Deploy Node to Worker Node
  copy:
    src: "/home/{{ groups.master[0] }}/var/lib/rancher/k3s/server/node-token"
    dest: "{{K8S_OFFLINE_DIR}}/node-token"

- name: Cat nodetoken
  shell: cat {{K8S_OFFLINE_DIR}}/node-token
  register: NODE_TOKEN
  
- name: Load k3s Images
  shell: for f in "{{ TARBALL_PATH }}"/k3s-airgap-images-amd64.tar; do docker load -i $f; done

- name: k3s files chmod
  command: sudo chmod a+x "{{ TARBALL_PATH }}"/k3s "{{ TARBALL_PATH }}"/k3s-install.sh

- name: k3s files copy
  command: sudo cp "{{ TARBALL_PATH }}"/k3s /usr/local/bin/

- name: Install k3s
  shell: INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://{{ groups.master[0] }}:6443 K3S_TOKEN={{ NODE_TOKEN.stdout }}  "{{ TARBALL_PATH }}"/k3s-install.sh

- name: Create k3s directory
  shell: mkdir -p /etc/rancher/k3s

- name: Copy registries.yaml From Deploy Node to Worker Node
  copy:
    src: "{{role_path}}/files/registries.yaml”
    dest: /etc/rancher/k3s/registries.yaml

- name: Set insecure-registries IP in /etc/rancher/k3s/registries.yaml
  replace:
    path: /etc/rancher/k3s/registries.yaml
    regexp: PRIVATE_REGISTRY_IP
    replace: "{{ groups.master[0] }}"

- name: Restart k3s-agent
  shell: systemctl restart k3s-agent
