version: "3"
services:
  mecm-applcm-apprulemgr:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-appclm-apprulemgr:v1.1.1
    depends_on:
  　　- postgres
  　environment:
      LOG_DIR: /usr/app/log
      MEP_SERVER_ADDR: mep-mm5.mep
      MEP_SERVER_PORT: 80 
      APPRULEMGR_DB_ADAPTER: pgDb
      LISTEN_IP: 
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
      APPRULEMGR_DB_PASSWORD: "te9Fmv%qaq"

    volume:
      - /tmp/keys:/usr/app/ssl

  mecm-applcm-k8splugin:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-k8splugin:v1.1.1
    depends_on:
  　　- postgres
    environment:     
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      K8S_PLUGIN_DB_PASSWORD: te9Fmv%qaq
      JWT_PUBLIC_KEY: publicKey
      
  mecm-applcm-lcmcontroller:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-lcmcontroller:v1.1.1
    depends_on:
  　　- postgres
    environment:     
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      API_GW_ADDR: mepauth.mep
      API_GW_PORT: "10443"
      K8S_PLUGIN: mecm-mepm-k8splugin
      K8S_PLUGIN_PORT: "8095"
      OPENSTACK_PLUGIN: mecm-mepm-osplugin
      OPENSTACK_PLUGIN_PORT: "8234" 
      LISTEN_IP: ${ENV_IP}
      LCM_CNTLR_DB_PASSWORD: te9Fmv%qaq
      JWT_PUBLIC_KEY: publicKey
  
  mepm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepm-fe:v1.1.1
  　ports:
  　　- 30097:8443
  　depends_on:
  　　- postgres
        
  postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres:12.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "te9Fmv%qaq"
      POSTGRES_DB: root
