version: "3"
services:
  mecm-mepm-apprulemgr:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-apprulemgr:v1.1.1
    depends_on:
      - mepm-postgres
    restart: always
    environment:
      LOG_DIR: /usr/app/log
      MEP_SERVER_ADDR: ${ENV_IP}
      MEP_SERVER_PORT: 8088
      APPRULEMGR_DB_ADAPTER: "pgDb"
      LISTEN_IP: ${ENV_IP}
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
      APPRULEMGR_DB_PASSWORD: "te9Fmv%qaq"
    volumes:
      - /tmp/keys/ca.crt:/usr/app/ssl/ca.crt
      - /tmp/keys/tls.crt:/usr/app/ssl/server_tls.crt
      - /tmp/keys/tls.key:/usr/app/ssl/server_tls.key

  mecm-mepm-k8splugin:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-k8splugin:v1.1.1
    depends_on:
      - mepm-postgres
    restart: always
    environment:     
      LOG_DIR: /usr/app/log
      LISTEN_IP: ${ENV_IP}
      K8S_PLUGIN_DB_PASSWORD: "te9Fmv%qaq"
      K8S_PLUGIN_DB_HOST: ${ENV_IP}
      K8S_PLUGIN_DB_PORT: 8432
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
    volumes:
      - /tmp/keys/ca.crt:/usr/app/ssl/ca.crt
      - /tmp/keys/tls.crt:/usr/app/ssl/server_tls.crt
      - /tmp/keys/tls.key:/usr/app/ssl/server_tls.key
      
  mecm-mepm-lcmcontroller:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm:v1.1.1
    depends_on:
      - mepm-postgres
    restart: always
    environment:     
      LOG_DIR: /usr/app/log
      API_GW_ADDR: ${ENV_IP}
      API_GW_PORT: "10443"
      K8S_PLUGIN: "mecm-mepm-k8splugin"
      K8S_PLUGIN_PORT: "8095"
      OPENSTACK_PLUGIN: "mecm-mepm-osplugin"
      OPENSTACK_PLUGIN_PORT: "8234" 
      LISTEN_IP: ${ENV_IP}
      LCM_CNTLR_DB_PASSWORD: "te9Fmv%qaq"
      LCM_CNTLR_DB_HOST: ${ENV_IP}
      LCM_CNTLR_DB_PORT: 8432
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
    volumes:
      - /tmp/keys/ca.crt:/usr/app/ssl/ca.crt
      - /tmp/keys/tls.crt:/usr/app/ssl/server_tls.crt
      - /tmp/keys/tls.key:/usr/app/ssl/server_tls.key

  mecm-mepm-osplugin:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mecm-applcm-osplugin:v1.1.1
    depends_on:
      - mepm-postgres
    restart: always
    environment:
      LISTEN_IP: mecm-mepm-osplugin
      DB_PASSWORD: "te9Fmv%qaq"
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
    volumes:
      - /tmp/keys/ca.crt:/usr/app/ssl/ca.crt
      - /tmp/keys/tls.crt:/usr/app/ssl/server_tls.crt
      - /tmp/keys/tls.key:/usr/app/ssl/server_tls.key
  
  mepm-fe:
    image: swr.ap-southeast-1.myhuaweicloud.com/edgegallery/mepm-fe:v1.1.1
    restart: always
    ports:
      - 30097:8200
    volumes:
      - ./mepm-fe-data/nginx.conf:/etc/nginx/nginx.conf

  mepm-postgres:
    image: swr.ap-southeast-1.myhuaweicloud.com/eg-common/postgres:12.3
    ports:
      - 8432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "te9Fmv%qaq"
      POSTGRES_DB: root
    volumes:
      - ./postgres-data/:/docker-entrypoint-initdb.d/
