- name: Get All Non-Running Pods
  shell: kubectl get pods --all-namespaces --field-selector=status.phase!=Running
  register: nonRunningPod

- debug:
    msg: "Failed Pods are {{ nonRunningPod.stdout }}"
  when: nonRunningPod.stderr != "No resources found"

- fail:
    msg: "EdgeGallery Deployment Failed ....."
  when: nonRunningPod.stderr != "No resources found"

- name: Get Deployed Helm Release
  shell: helm list -A
  register: releasesDeployed
  ignore_errors: yes

- debug:
    msg: "APPSTORE PORTAL   : https://{{ PORTAL_IP }}:{{ APPSTORE_PORT }}"
  when: releasesDeployed is succeeded and APPSTORE_HELM_RELEASE_NAME in releasesDeployed.stdout

- debug:
    msg: "DEVELOPER PORTAL   : https://{{ PORTAL_IP }}:{{ DEVELOPER_PORT }}"
  when: releasesDeployed is succeeded and DEVELOPER_HELM_RELEASE_NAME in releasesDeployed.stdout

- debug:
    msg: "MECM PORTAL   : https://{{ PORTAL_IP }}:{{ MECM_PORT }}"
  when: releasesDeployed is succeeded and MECM_FE_HELM_RELEASE_NAME in releasesDeployed.stdout

- debug:
    msg: "ATP PORTAL   : https://{{ PORTAL_IP }}:{{ ATP_PORT }}"
  when: releasesDeployed is succeeded and ATP_HELM_RELEASE_NAME in releasesDeployed.stdout

- name: EdgeGallery Got Deployed SuccessFully
  shell: |
    echo -e "{{ PURPLE }}                             *" > /dev/tty
    echo -e "{{ PURPLE }}                           *   *" > /dev/tty
    echo -e "{{ PURPLE }}                         *       *" > /dev/tty
    echo -e "{{ PURPLE }}                       *{{ GREEN }}          *" > /dev/tty
    echo -e "{{ PURPLE }}                       * *{{ GREEN }}      *" > /dev/tty
    echo -e "{{ PURPLE }}                       *    *{{ GREEN }} *     *{{ PURPLE }}     EDGE" > /dev/tty
    echo -e "{{ PURPLE }}                       *{{ GREEN }}    *    *  *     GALLERY" > /dev/tty
    echo -e "{{ PURPLE }}                       *{{ GREEN }}    *     *" > /dev/tty
    echo -e "{{ PURPLE }}                         *{{ GREEN }}  *   *" > /dev/tty
    echo -e "{{ PURPLE }}                           *{{ GREEN }} * *" > /dev/tty
    echo -e "{{ GREEN }}                             *{{ NC }}" > /dev/tty
  when: nonRunningPod.stderr == "No resources found"
  ignore_errors: yes