#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

---

- name: Deploy healthcheck-m
  shell: |
    helm install --wait healthcheck-m-edgegallery {{ HELM_CHARTS_PATH }}/edgegallery/healthcheck-m-{{ HELM_TAG }}.tgz \
    --set images.healthcheckm.repository={{ healthcheckm_images_repository }} \
    --set images.healthcheckm.tag={{ EG_IMAGE_TAG }} \
    --set images.healthcheckm.pullPolicy={{ healthcheckm_images_pullPolicy }} \
    --set healthcheckm.localIp={{ MASTER_IP }}

- name: Check healthcheck-m Status
  uri:
    url: "http://{{ MASTER_IP }}:{{ HEALTHCHECK_M_PORT }}/health-check/v1/center/health"
    validate_certs: no
