---

- name: Deploy MECM-FE
  shell: |
    helm install --wait mecm-fe-edgegallery {{ HELM_CHARTS_PATH }}/edgegallery/mecm-fe-{{ HELM_TAG }}.tgz \
    --set global.oauth2.authServerAddress=https://{{ ansible_default_ipv4['address'] }}:{{ USER_MGMT_PORT }} \
    --set images.mecmFe.repository={{ mecm_fe_images_mecmFe_repository }} \
    --set images.initservicecenter.repository={{ mecm_fe_images_initservicecenter_repository }} \
    --set images.mecmFe.tag={{ mecm_fe_images_mecmFe_tag }} \
    --set images.mecmFe.pullPolicy={{ mecm_fe_images_mecmFe_pullPolicy }} \
    --set images.initservicecenter.pullPolicy={{ mecm_fe_images_initservicecenter_pullPolicy }} \
    --set global.ssl.enabled={{ mecm_fe_global_ssl_enabled }} \
    --set global.ssl.secretName={{ mecm_fe_global_ssl_secretName }} \
    --set global.persistence.enabled={{ ENABLE_PERSISTENCE }}
