#
#   Copyright 2021 Huawei Technologies Co., Ltd.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

K8S_TARBALL_FILE: "{{ TARBALL_PATH }}/kubernetes_offline_installer.tar.gz"
K8S_OFFLINE_DIR: "{{ TARBALL_PATH }}/kubernetes_offline_installer"

DOCKER_TARBALL_FILE: "{{ K8S_OFFLINE_DIR }}/docker/docker.tgz"
DOCKER_OFFLINE_DIR: "{{ K8S_OFFLINE_DIR }}/docker"
DOCKER_REGISTRY_IMAGE: "{{ TARBALL_PATH }}/registry/registry-2.tar.gz"
REGISTRY_CONTAINER_NAME: docker-registry
REGISTRY_IMAGE_NAME: eg-common/registry:2

K8S_DOCKER_IMAGES:
  - k8s.gcr.io/kube-proxy:v1.23.3
  - k8s.gcr.io/kube-controller-manager:v1.23.3
  - k8s.gcr.io/kube-apiserver:v1.23.3
  - k8s.gcr.io/kube-scheduler:v1.23.3
  - k8s.gcr.io/pause:3.6
  - k8s.gcr.io/coredns/coredns:v1.8.6
  - k8s.gcr.io/etcd:3.5.1-0
  - k8s.gcr.io/metrics-server/metrics-server:v0.3.7
  - calico/node:v3.15.1
  - calico/cni:v3.15.1
  - calico/kube-controllers:v3.15.1
  - calico/pod2daemon-flexvol:v3.15.1
  - nginx:stable
  - k8s.gcr.io/pause:3.4.1
  - k8s.gcr.io/coredns/coredns:1.8.0
  - k8s.gcr.io/etcd:3.4.13-0
  
 
  
K8S_TAR_IMAGE: k8s_images.tar.gz

CNI_BIN_PATH: /opt/cni/bin

HELM_VERSION: v3.8.0
HELM_TARBALL_FILE: "{{ TARBALL_PATH }}/helm/helm-{{ HELM_VERSION }}-linux-{{ ARCH }}.tar.gz"
HELM_OFFLINE_DIR: "{{ TARBALL_PATH }}/helm"

NFS_DEB_PATH: "{{ TARBALL_PATH }}/nfs/deb"
NFS_IMAGE: "{{ TARBALL_PATH }}/nfs/images/nfs_images.tar.gz"
NFS_PATH: "/edgegallery/data"
NFS_CHART_FILE: "{{ HELM_CHARTS_DIR }}/stable/nfs-subdir-external-provisioner-4.0.16.tgz"
nfs_image_repository: eg-common/k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
nfs_image_tag: v4.0.2
